/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package form;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.Produk;

/**
 *
 * @author RHYZONE
 */
public class FrmProduk extends javax.swing.JFrame {
    Produk produk = new Produk();
    /**
     * Creates new form FrmProduk
     */
    
    public FrmProduk() {
        initComponents();
        this.setLocationRelativeTo(null);
        bt_hapus.setEnabled(false);
        bt_ubah.setEnabled(false);
    }
    
    public FrmProduk(String id) {
        initComponents();
        this.setLocationRelativeTo(null);
        bt_simpan.setEnabled(false);
        tx_kode.setEditable(false);
        this.cari(id);        
    }
    
    private void cari(String id)
    {
        try{
            produk.kode_produk = id;
            ArrayList data = produk.cari();
            tx_kode.setText((String)data.get(0));
            tx_nama.setText((String)data.get(1));
            tx_harga.setText(String.valueOf(data.get(2)));
            tx_stok.setText(String.valueOf(data.get(3)));
            
        }
        catch(Exception ex) {
            JOptionPane.showMessageDialog(null, "Data Gagal Ditampilkan " + ex.getMessage());
        }
    }
    
    private void setData() {
        try {
            produk.kode_produk = tx_kode.getText();
            produk.nama_produk = tx_nama.getText();
            if(tx_harga.getText().equals("")) {
                tx_harga.setText("0");
            }
            if(tx_stok.getText().equals("")) {
                tx_stok.setText("0");
            }
            produk.harga = Integer.parseInt(tx_harga.getText());
            produk.stok = Integer.parseInt(tx_stok.getText());
        }
        catch(Exception ex) {
            
        }
    }
    
    private void kosong() {
        tx_kode.setText("");
        tx_nama.setText("");
        tx_harga.setText("0");
        tx_stok.setText("0");
    }
    
    private int validasi() {
        int hasil = 0;
        if(produk.kode_produk.equals("") || produk.nama_produk.equals("")) {
            hasil = 1;
        }   
        if(produk.harga < 0 || produk.stok < 0) {
            hasil = 1;
        }
        return hasil;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tx_stok = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        tx_kode = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tx_nama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tx_harga = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        bt_simpan = new javax.swing.JButton();
        bt_ubah = new javax.swing.JButton();
        bt_hapus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        tx_stok.setText("0");

        jLabel1.setText("FORM PRODUK");

        jLabel2.setText("Kode Produk");

        jLabel3.setText("Nama Produk");

        jLabel4.setText("Harga");

        tx_harga.setText("0");

        jLabel5.setText("Stok");

        bt_simpan.setText("Simpan");
        bt_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_simpanActionPerformed(evt);
            }
        });

        bt_ubah.setText("Ubah");
        bt_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ubahActionPerformed(evt);
            }
        });

        bt_hapus.setText("Hapus");
        bt_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_hapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tx_kode, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                            .addComponent(tx_harga)
                            .addComponent(tx_nama)
                            .addComponent(tx_stok)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bt_simpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_ubah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_hapus)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tx_kode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tx_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tx_harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tx_stok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_simpan)
                    .addComponent(bt_ubah)
                    .addComponent(bt_hapus))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_simpanActionPerformed
        // TODO add your handling code here:
        this.setData();
        int hasil = this.validasi();
        if(hasil == 0) {
            int pilih = JOptionPane.showConfirmDialog(null, "Anda yakin ingin menginput data ini?", "Pilih", JOptionPane.YES_NO_OPTION);
            if(pilih == JOptionPane.YES_OPTION) {
                produk.input();
                JOptionPane.showMessageDialog(null, "Data berhasil diinput");
                this.kosong();
            }
        }
        else {
            JOptionPane.showMessageDialog(null, "Data harap diisi dengan benar");
        }
    }//GEN-LAST:event_bt_simpanActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        FrmDaftarProduk obj = new FrmDaftarProduk();
        obj.show();
    }//GEN-LAST:event_formWindowClosed

    private void bt_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ubahActionPerformed
        // TODO add your handling code here:
        this.setData();
        int hasil = this.validasi();
        if(hasil == 0) {
            int pilih = JOptionPane.showConfirmDialog(null, "Anda yakin ingin mengubah data ini?", "Pilih", JOptionPane.YES_NO_OPTION);
            if(pilih == JOptionPane.YES_OPTION) {
                produk.edit();
                JOptionPane.showMessageDialog(null, "Data berhasil diubah");
                this.kosong();
            }
        }
        else {
            JOptionPane.showMessageDialog(null, "Data harap diisi dengan benar");
        }
    }//GEN-LAST:event_bt_ubahActionPerformed

    private void bt_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_hapusActionPerformed
        // TODO add your handling code here:
        this.setData();
        int hasil = this.validasi();
        if(hasil == 0) {
            int pilih = JOptionPane.showConfirmDialog(null, "Anda yakin ingin menghapus data ini?", "Pilih", JOptionPane.YES_NO_OPTION);
            if(pilih == JOptionPane.YES_OPTION) {
                produk.hapus();
                JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
                this.kosong();
            }
        }
        else {
            JOptionPane.showMessageDialog(null, "Data harap diisi dengan benar");
        }
    }//GEN-LAST:event_bt_hapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmProduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmProduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmProduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmProduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmProduk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_hapus;
    private javax.swing.JButton bt_simpan;
    private javax.swing.JButton bt_ubah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField tx_harga;
    private javax.swing.JTextField tx_kode;
    private javax.swing.JTextField tx_nama;
    private javax.swing.JTextField tx_stok;
    // End of variables declaration//GEN-END:variables
}
