/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package form;

/**
 *
 * @author RHYZONE
 */
import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.Produk;
import model.TransaksiDetil;

public class FrmTransaksiDetil extends javax.swing.JFrame {
    TransaksiDetil detil = new TransaksiDetil();
    /**
     * Creates new form FrmTransaksiDetil
     */
    public FrmTransaksiDetil() {
        initComponents();
        this.setLocationRelativeTo(null);
        bt_hapus.setEnabled(false);
        bt_ubah.setEnabled(false);
        tx_id.setEnabled(false);
        this.tampilKode();
    }
    
    public FrmTransaksiDetil(String id) {
        initComponents();
        this.setLocationRelativeTo(null);
        bt_simpan.setEnabled(false);
        tx_id.setEditable(false);
        tx_nomor.setEditable(false);
        this.tampilKode();
        this.cari(id);        
    }
    
    private void tampilKode() {
        Produk obj = new Produk();
        ArrayList data = obj.tampil();
        for(int i = 0; i < data.size() - 1; i+=4) {
            cb_kode.addItem(data.get(i));
        }
    }
    
    private void cari(String id)
    {
        try{
            detil.id = Integer.parseInt(id);
            ArrayList data = detil.cari();
            tx_id.setText((String)data.get(0));
            tx_nomor.setText((String)data.get(1));
            cb_kode.setSelectedItem((String)data.get(2));
            tx_jumlah.setText((String)data.get(3));
            tx_harga.setText((String)data.get(4));
            
        }
        catch(Exception ex) {
            JOptionPane.showMessageDialog(null, "Data Gagal Ditampilkan " + ex.getMessage());
        }
    }
    
    private void setData() {
        try {
            detil.id = Integer.parseInt(tx_id.getText());
            detil.nomor_transaksi = tx_nomor.getText();
            detil.kode_produk = cb_kode.getSelectedItem().toString();
            detil.jumlah = Integer.parseInt(tx_jumlah.getText());
            detil.harga_transaksi = Integer.parseInt(tx_harga.getText());
        }
        catch(Exception ex) {
            
        }
    }
    
    private void kosong() {
        tx_id.setText("");
        tx_nomor.setText("");
        cb_kode.setSelectedIndex(0);
        tx_jumlah.setText("0");
        tx_harga.setText("0");
    }
    
    private int validasi() {
        int hasil = 0;
        if(detil.jumlah < 0 || detil.harga_transaksi < 0) {
            hasil = 1;
        }   
        return hasil;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        tx_id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cb_kode = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        tx_jumlah = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tx_harga = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        bt_simpan = new javax.swing.JButton();
        bt_ubah = new javax.swing.JButton();
        bt_hapus = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        tx_nomor = new javax.swing.JTextField();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("FORM TRANSAKSI DETIL");

        jLabel2.setText("ID");

        jLabel3.setText("Kode Produk");

        jLabel4.setText("Jumlah");

        tx_jumlah.setText("0");
        tx_jumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_jumlahActionPerformed(evt);
            }
        });

        jLabel5.setText("Harga Transaksi");

        tx_harga.setText("0");

        bt_simpan.setText("Simpan");
        bt_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_simpanActionPerformed(evt);
            }
        });

        bt_ubah.setText("Ubah");
        bt_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ubahActionPerformed(evt);
            }
        });

        bt_hapus.setText("Hapus");
        bt_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_hapusActionPerformed(evt);
            }
        });

        jLabel7.setText("Nomor Transaksi");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                        .addComponent(tx_id, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb_kode, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tx_jumlah)
                            .addComponent(tx_harga)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bt_simpan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt_ubah)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt_hapus)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(21, 21, 21)
                        .addComponent(tx_nomor)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tx_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(tx_nomor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(cb_kode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(tx_jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tx_harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_simpan)
                    .addComponent(bt_ubah)
                    .addComponent(bt_hapus))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tx_jumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_jumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_jumlahActionPerformed

    private void bt_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_simpanActionPerformed
        // TODO add your handling code here:
        this.setData();
        int hasil = this.validasi();
        if(hasil == 0) {
            int pilih = JOptionPane.showConfirmDialog(null, "Anda yakin ingin menginput data ini?", "Pilih", JOptionPane.YES_NO_OPTION);
            if(pilih == JOptionPane.YES_OPTION) {
                detil.input();
                JOptionPane.showMessageDialog(null, "Data berhasil diinput");
                this.kosong();
            }
        }
        else {
            JOptionPane.showMessageDialog(null, "Data harap diisi dengan benar");
        }
    }//GEN-LAST:event_bt_simpanActionPerformed

    private void bt_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ubahActionPerformed
        // TODO add your handling code here:
         this.setData();
        int hasil = this.validasi();
        if(hasil == 0) {
            int pilih = JOptionPane.showConfirmDialog(null, "Anda yakin ingin mengubah data ini?", "Pilih", JOptionPane.YES_NO_OPTION);
            if(pilih == JOptionPane.YES_OPTION) {
                detil.edit();
                JOptionPane.showMessageDialog(null, "Data berhasil diubah");
                this.kosong();
            }
        }
        else {
            JOptionPane.showMessageDialog(null, "Data harap diisi dengan benar");
        }
    }//GEN-LAST:event_bt_ubahActionPerformed

    private void bt_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_hapusActionPerformed
        // TODO add your handling code here:
        this.setData();
        int hasil = this.validasi();
        if(hasil == 0) {
            int pilih = JOptionPane.showConfirmDialog(null, "Anda yakin ingin menghapus data ini?", "Pilih", JOptionPane.YES_NO_OPTION);
            if(pilih == JOptionPane.YES_OPTION) {
                detil.hapus();
                JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
                this.kosong();
            }
        }
        else {
            JOptionPane.showMessageDialog(null, "Data harap diisi dengan benar");
        }
    }//GEN-LAST:event_bt_hapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTransaksiDetil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTransaksiDetil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTransaksiDetil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTransaksiDetil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTransaksiDetil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_hapus;
    private javax.swing.JButton bt_simpan;
    private javax.swing.JButton bt_ubah;
    private javax.swing.JComboBox cb_kode;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField tx_harga;
    private javax.swing.JTextField tx_id;
    private javax.swing.JTextField tx_jumlah;
    private javax.swing.JTextField tx_nomor;
    // End of variables declaration//GEN-END:variables
}
