/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package form;

/**
 *
 * @author RHYZONE
 */
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Pegawai;
import model.TransaksiHeader;
import model.TransaksiDetil;

public class FrmTransaksi extends javax.swing.JFrame {
    DefaultTableModel model;
    TransaksiHeader header = new TransaksiHeader();
    TransaksiDetil detil = new TransaksiDetil();
    /**
     * Creates new form FrmTransaksi
     */
   public FrmTransaksi() {
        initComponents();
        this.setLocationRelativeTo(null);
        bt_hapus.setEnabled(false);
        bt_ubah.setEnabled(false);
        this.tampilKode();
    }
    
    public FrmTransaksi(String id) {
        initComponents();
        this.setLocationRelativeTo(null);
        tx_nomor.setEditable(false);
        this.tampilKode();
        this.cari(id);    
        this.tampil(id);
    }
    private void tampilKode() {
        Pegawai obj = new Pegawai();
        ArrayList data = obj.tampil();
        for(int i = 0; i < data.size() - 1; i+=6) {
            cb_kode.addItem(data.get(i));
        }
    }
    private void cari(String id)
    {
        try{
            header.nomor_transaksi = id;
            ArrayList data = header.cari();
            tx_nomor.setText((String)data.get(0));
            Date date = new SimpleDateFormat("yyyy-MM-dd").parse((String)data.get(1));
            dt_tanggal.setDate(date);
            tx_harga.setText(String.valueOf(data.get(2)));
            cb_kode.setSelectedItem((String)data.get(3));
            
        }
        catch(Exception ex) {
            JOptionPane.showMessageDialog(null, "OK Data Gagal Ditampilkan " + ex.getMessage());
        }
    }
    
    private void setData() {
        try {
            header.nomor_transaksi = tx_nomor.getText();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            header.tanggal_transaksi = sdf.format(dt_tanggal.getDate());
            header.total_harga = Integer.parseInt(tx_harga.getText());
            header.kode_pegawai = cb_kode.getSelectedItem().toString();
        }
        catch(Exception ex) {
            
        }
    }
    
    private void kosong() {
        tx_nomor.setText("");
        Date date = new Date();
        dt_tanggal.setDate(date);
        tx_harga.setText("0");
        cb_kode.setSelectedIndex(0);
    }
    
    private int validasi() {
        int hasil = 0;
        if(header.nomor_transaksi.equals("")) {
            hasil = 1;
        }   
        Date date = new Date();
        if(dt_tanggal.getDate().after(date)) {
            hasil = 1;
        }
        if(header.total_harga < 0) {
            hasil = 1;
        }
        return hasil;
    }
    
     private void tampil(String nomor) {
        try{
            ArrayList data = detil.carinomor();
            for(int i = 0;i < data.size()-1;i+=5)
            {
                int id = (int)data.get(i);
                String kode = (String)data.get(i+2);
                int jumlah = (int)data.get(i+3);
                int harga = (int)data.get(i+4);

                String[] data_field = {String.valueOf(id),kode.trim(),String.valueOf(jumlah),String.valueOf(harga)};
                model = (DefaultTableModel)tb_detil.getModel();
                model.addRow(data_field);
            }
        }
        catch(Exception ex) {
            JOptionPane.showMessageDialog(null, "Data Gagal Ditampilkan" + ex.getMessage());
            ex.printStackTrace();
        }
    }
    
    private String cari() {
        int baris = tb_detil.getSelectedRow();
        model = (DefaultTableModel) tb_detil.getModel();
        String id = model.getValueAt(baris,0).toString();
        return id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        tx_nomor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        dt_tanggal = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        tx_harga = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cb_kode = new javax.swing.JComboBox();
        jSeparator2 = new javax.swing.JSeparator();
        bt_ubah = new javax.swing.JButton();
        bt_hapus = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_detil = new javax.swing.JTable();
        bt_tambah = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("FORM TRANSAKSI");

        jLabel2.setText("Nomor Transaksi");

        jLabel3.setText("Tanggal Transaksi");

        jLabel4.setText("Total Harga");

        jLabel5.setText("Kode Pegawai");

        bt_ubah.setText("Ubah");
        bt_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ubahActionPerformed(evt);
            }
        });

        bt_hapus.setText("Hapus");
        bt_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_hapusActionPerformed(evt);
            }
        });

        tb_detil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Kode Produk", "Jumlah", "Harga Transaksi"
            }
        ));
        jScrollPane1.setViewportView(tb_detil);

        bt_tambah.setText("Tambah Data");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tx_nomor)
                            .addComponent(dt_tanggal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tx_harga)
                            .addComponent(cb_kode, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jSeparator3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bt_tambah)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(bt_ubah)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(bt_hapus))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 5, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tx_nomor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(dt_tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(tx_harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cb_kode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_ubah)
                    .addComponent(bt_hapus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_tambah)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ubahActionPerformed
        // TODO add your handling code here:
        this.setData();
        int hasil = this.validasi();
        if(hasil == 0) {
            int pilih = JOptionPane.showConfirmDialog(null, "Anda yakin ingin mengubah data ini?", "Pilih", JOptionPane.YES_NO_OPTION);
            if(pilih == JOptionPane.YES_OPTION) {
                header.edit();
                JOptionPane.showMessageDialog(null, "Data berhasil diubah");
                this.kosong();
            }
        }
        else {
            JOptionPane.showMessageDialog(null, "Data harap diisi dengan benar");
        }
    }//GEN-LAST:event_bt_ubahActionPerformed

    private void bt_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_hapusActionPerformed
        // TODO add your handling code here:
        this.setData();
        int hasil = this.validasi();
        if(hasil == 0) {
            int pilih = JOptionPane.showConfirmDialog(null, "Anda yakin ingin menghapus data ini?", "Pilih", JOptionPane.YES_NO_OPTION);
            if(pilih == JOptionPane.YES_OPTION) {
                header.hapus();
                JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
                this.kosong();
            }
        }
        else {
            JOptionPane.showMessageDialog(null, "Data harap diisi dengan benar");
        }
    }//GEN-LAST:event_bt_hapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTransaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_hapus;
    private javax.swing.JButton bt_tambah;
    private javax.swing.JButton bt_ubah;
    private javax.swing.JComboBox cb_kode;
    private com.toedter.calendar.JDateChooser dt_tanggal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable tb_detil;
    private javax.swing.JTextField tx_harga;
    private javax.swing.JTextField tx_nomor;
    // End of variables declaration//GEN-END:variables
}
